### ISSUE TITLE
Fail in LA.pdf 02

### ISSUE THREAD

**Issue by Aksinya-Bykova** [isagila/tesc#27]
В задаче о перпендикуляре на 5 странице, похоже, опечатки. Два раза не хватает взятия квадрата нормы
![image](https://github.com/isagila/tesc/assets/108536260/073eed20-5c9f-46e9-a949-eab2a7aad6b0)

**Comment by isagila** [comment]
Спасибо!

Исправлено в https://github.com/tesc-tex/02-LA/commit/1a785896b0cd15d7b5d1d178f3f78b48b999919e
